name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      
      - name: bootstrap
        run: script/bootstrap

      - name: test 
        run: script/cibuild

      - name: lint
        run: script/lint